version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "@vitejs/plugin-react"
        versions: [">= 6.0.0"]
      - dependency-name: "express"
        versions: [">= 5.0.0"]
