export type UserRole = 'client' | 'lawyer' | 'admin';

export interface CyberComplaint {
  id: string;
  clientId: string;
  platformName: string;
  targetUrl: string;
  abuseType: 'Harassment' | 'Hate Speech' | 'Defamation' | 'Impersonation' | 'Other';
  impactDescription: string;
  createdAt: string;
  status: 'Pending' | 'Reviewing' | 'ActionTaken' | 'Closed';
}

export interface User {
  id: string;
  name: string;
  email: string;
  role: UserRole;
  phone?: string;
  isVerifiedLawyer?: boolean;
  barCouncilNumber?: string;
  stateBarCouncil?: string;
  practiceLocation?: string;
  yearsExperience?: number;
  specialization?: string[];
  membershipActive: boolean;
  membershipPlan?: 'client_annual' | 'advocate_annual' | 'advocate_monthly';
  membershipExpiresAt?: string;
  avatar?: string;
  consultationFee?: number;
  bio?: string;
  rating?: number;
  reviewCount?: number;
  casesWon?: number;
  // 21-Day Free Trial & Auto-Payment Mandate (Option A)
  trialStartDate?: string;
  trialEndsAt?: string;
  trialDaysRemaining?: number;
  isTrialActive?: boolean;
  autoPaymentMandateActive?: boolean;
  mandateMethod?: 'upi_autopay' | 'card_mandate' | 'netbanking_emandate' | 'none';
  mandateDetails?: string;
  nextBillingDate?: string;
  mandateStatus?: 'active' | 'pending' | 'cancelled';
  trialCancelled?: boolean;
  autoDebitAmount?: number;
}

export interface CaseDocument {
  id: string;
  title: string;
  fileName: string;
  fileType: 'pdf' | 'docx' | 'image' | 'scan';
  fileSize: string;
  uploadedAt: string;
  uploadedBy: string;
  fileCategory: 'Petition' | 'Affidavit' | 'Evidence' | 'Court Order' | 'Vakalatnama' | 'Notice' | 'Forensic Report';
  isRestricted: boolean; // Only verified lawyers can view
  fileUrl?: string;
  documentHash: string;
  pageCount: number;
  summary?: string;
}

export interface Hearing {
  id: string;
  hearingDate: string;
  courtRoom: string;
  judgeName: string;
  stage: string;
  purpose: string;
  notes?: string;
  adjournmentReason?: string;
  status: 'Scheduled' | 'Completed' | 'Adjourned';
}

export interface CaseMatter {
  id: string;
  caseNumber: string;
  cnrNumber: string;
  title: string;
  caseType: 'Commercial Dispute' | 'Constitutional Writ' | 'Cyber Crime' | 'Civil & Property' | 'Corporate Arbitration' | 'Criminal Defense' | 'Family Law' | 'Public Interest Litigation (PIL)';
  filingDate: string;
  courtName: string;
  jurisdiction: string;
  bench: string;
  judgeName: string;
  petitioner: string;
  respondent: string;
  clientId: string; // Used for strict client isolation
  clientName: string;
  clientEmail: string;
  assignedLawyerId?: string;
  assignedLawyerName?: string;
  status: 'Filing' | 'Scrutiny' | 'Notice' | 'Evidence' | 'Arguments' | 'Reserved' | 'Disposed';
  stageDescription: string;
  daysElapsed: number;
  estimatedDisposalDays: number;
  delayRiskScore: 'Low' | 'Moderate' | 'Critical';
  delayDays: number;
  bottleneckReason?: string;
  nextHearingDate?: string;
  hearings: Hearing[];
  documents: CaseDocument[];
  summaryBrief?: string;
}

export interface LawyerReview {
  id: string;
  lawyerId: string;
  clientId: string;
  clientName: string;
  clientAvatar?: string;
  rating: number; // 1 to 5
  caseType: string;
  caseOutcome: 'Won' | 'Compromised' | 'Ongoing' | 'Lost';
  comment: string;
  courtName?: string;
  verifiedLitigant: boolean;
  createdAt: string;
}

export interface LawyerProfile {
  id: string;
  name: string;
  barCouncilNumber: string;
  stateBarCouncil: string;
  isVerified: boolean;
  specialization: string[];
  experienceYears: number;
  courts: string[];
  rating: number;
  reviewsCount: number;
  consultationFee: number;
  location: string;
  bio: string;
  casesResolved: number;
  activeCasesCount: number;
  casesTotal: number;
  casesWon: number;
  casesLost: number;
  casesCompromised: number;
  casesOngoing: number;
  winRate: number;
  compromiseRate?: number;
  grade: 'A+' | 'A' | 'B+' | 'B';
  tierTitle?: string;
  badges: string[];
  reviews?: LawyerReview[];
  contactEmail: string;
  phone: string;
  availableDays: string[];
  avatar: string;
}

export interface PaymentInvoice {
  id: string;
  invoiceNumber: string;
  userId: string;
  userName: string;
  userRole: UserRole;
  planName: string;
  planDuration: string;
  amount: number;
  taxAmount: number;
  totalAmount: number;
  currency: string;
  status: 'Paid' | 'Pending' | 'Failed';
  paymentMethod: string;
  transactionId: string;
  paidAt: string;
  expiresAt: string;
}

export interface DelayMetric {
  category: string;
  avgStandardDays: number;
  justiceBridgeAvgDays: number;
  reductionPercentage: number;
}

export interface ConsultationBooking {
  id: string;
  clientId: string;
  clientName: string;
  clientEmail: string;
  clientPhone?: string;
  lawyerId: string;
  lawyerName: string;
  bookingDate: string;
  timeSlot: string;
  consultationType: 'Video Call' | 'In-Person Chamber' | 'Phone';
  matterSubject: string;
  status: 'Pending' | 'Confirmed' | 'Completed' | 'Rescheduled';
  fee: number;
  meetingLink?: string;
  notes?: string;
  createdAt: string;
}

export interface LanguageOption {
  code: string;
  name: string;
  nativeName: string;
  speechLocale: string;
}

export interface TranslationDictionary {
  overview: string;
  findLawyer: string;
  findCase: string;
  myCases: string;
  delayAnalytics: string;
  legalDocs: string;
  aiCounsel: string;
  voiceCaseFiler: string;
  consultations: string;
  membership: string;
  tagline: string;
  chooseLanguage: string;
  availableIn24: string;
  membershipNotification: string;
  clientAccount: string;
  advocateAccount: string;
  clientMembershipMsg: string;
  advocateMembershipMsg: string;
  payClientFeeBtn: string;
  payAdvocateFeeBtn: string;
  activeMembership: string;
  heroBadge: string;
  heroHeadline1: string;
  heroHeadline2: string;
  heroHeadline3: string;
  heroSubtitle: string;
  btnSpeakToFileCase: string;
  btnFindLawyer: string;
  btnFindCase: string;
  btnClientVault: string;
  btnJoinAdvocate: string;
  heroQuickSearchPlaceholder: string;
  quickLookup: string;
  openAdvocateVault: string;
  viewMyIsolatedCases: string;
  pillar1Title: string;
  pillar1Desc: string;
  pillar2Title: string;
  pillar2Desc: string;
  pillar3Title: string;
  pillar3Desc: string;
  strictRule1: string;
  strictRule2: string;
  daysSaved: string;
  advocateDirectory: string;
  connectVerifiedCounsels: string;
  filterAdvocatesDesc: string;
  browseAdvocatesBtn: string;
  caseTrackingDelayMonitor: string;
  trackLitigationsTitle: string;
  trackLitigationsDesc: string;
  searchCaseByCnrBtn: string;
  judicialDataSecurity: string;
  engineeredForConfidentiality: string;
  securityRule1Title: string;
  securityRule1Desc: string;
  securityRule2Title: string;
  securityRule2Desc: string;
  searchPlaceholder: string;
  filterByCourt: string;
  filterByCity: string;
  filterByPractice: string;
  consultFee: string;
  bookConsultation: string;
  verifiedAdvocate: string;
  noAdvocatesFound: string;
  noAdvocatesDesc: string;
  resetFilters: string;
  allCourtsJurisdictions: string;
  anyExperience: string;
  sortHighestRated: string;
  sortExperience: string;
  sortConsultFee: string;
  sortCasesWon: string;
  sortFeeDesc: string;
  verifiedOnly: string;
  bciVerifiedDirectoryBadge: string;
  completeBarVerificationBtn: string;
  yearsExperience: string;
  yearsActive: string;
  ratingLabel: string;
  verifiedBadge: string;
  pendingBadge: string;
  per30MinConsultation: string;
  queryingAdvocates: string;
  barEnrollment: string;
  experienceLabel: string;
  appearsBefore: string;
  detailsBtn: string;
  consultBtn: string;
  viewProfile: string;
  barVerified: string;
  verificationInProgress: string;
  practiceProfile: string;
  appearingCourts: string;
  availableSchedule: string;
  initialLegalAdvisoryFee: string;
  bookConsultationNow: string;
  advocatesCount: string;
  practiceAreaFilter: string;
  enterCnrOrNumber: string;
  searchCaseBtn: string;
  caseTrackerTitle: string;
  caseTrackerSubtitle: string;
  caseTrackerBadge: string;
  btnFileNewCasePetition: string;
  searchCaseInputPlaceholder: string;
  allCaseCategories: string;
  allRiskLevels: string;
  criticalDelay: string;
  moderateDelay: string;
  lowDelay: string;
  judicialLookupDesc: string;
  sortByDelay: string;
  sortByRecent: string;
  sortByNextHearing: string;
  noCasesFound: string;
  noCasesDesc: string;
  clearSearchQuery: string;
  caseStage: string;
  delayRiskScore: string;
  nextHearing: string;
  inspectCaseVault: string;
  searchingCauseLists: string;
  myCasesTitleClient: string;
  myCasesTitleLawyer: string;
  myCasesSubtitleClient: string;
  myCasesSubtitleLawyer: string;
  rule2BannerClient: string;
  rule1BannerLawyer: string;
  rule2ClientDesc: string;
  rule1LawyerDesc: string;
  rule1UnverifiedDesc: string;
  noActiveCasesYet: string;
  noActiveCasesDesc: string;
  btnFileFirstPetition: string;
  btnFileNewPetition: string;
  btnVoiceCaseFiler: string;
  totalCases: string;
  mattersCount: string;
  aiDelayAnalysis: string;
  analyzingDelay: string;
  openIsolatedVault: string;
  requestAdvocateInspection: string;
  delayAnalyticsTitle: string;
  delayAnalyticsSubtitle: string;
  delayAnalyticsBadge: string;
  delayDisclaimer: string;
  targetDelayReduction: string;
  timelineCompression: string;
  hearingTrackingSpeed: string;
  verifiedAdvocatesStat: string;
  litigationMattersActive: string;
  onboarded: string;
  realTime: string;
  disposalTimelinesTitle: string;
  disposalTimelinesDesc: string;
  traditional: string;
  delayCut: string;
  interactiveCalculatorTitle: string;
  interactiveCalculatorDesc: string;
  litigationType: string;
  courtTribunal: string;
  traditionalDisposalTime: string;
  timelineReduction: string;
  estimatedDisposal: string;
  estimatedTimeSaved: string;
  monthsCount: string;
  membershipTitle: string;
  membershipSubtitle: string;
  transparentMembership: string;
  clientJusticePass: string;
  annualClientMembership: string;
  advocatePracticePass: string;
  monthlyAdvocateMembership: string;
  yourAccountTier: string;
  perYearGst: string;
  perMonthGst: string;
  subscribeClientBtn: string;
  subscribeAdvocateBtn: string;
  legalDocEngineBadge: string;
  legalDocGeneratorTitle: string;
  legalDocGeneratorSubtitle: string;
  selectDocType: string;
  grading: string;
  lawyerGradingTitle: string;
  lawyerGradingSubtitle: string;
  casesTakenTotal: string;
  casesWon: string;
  casesLost: string;
  casesCompromised: string;
  casesOngoing: string;
  winRate: string;
  compromiseRate: string;
  clientReviews: string;
  gradingStarsBadges: string;
  writeReviewBtn: string;
  submitReview: string;
  ratingScore: string;
  caseOutcomeLabel: string;
  verifiedLitigantBadge: string;
  allOutcomes: string;
  gradeTier: string;
  originalAdvocatesTitle: string;
  performanceBreakdown: string;
  reviewPlaceholder: string;
  courtTribunalLabel: string;
  shareFeedback: string;
  yourRating: string;
  caseTypeLabel: string;
  selectOutcome: string;
  outcomeWon: string;
  outcomeCompromised: string;
  outcomeOngoing: string;
  outcomeLost: string;
  gradeAplusBadge: string;
  gradeABadge: string;
  gradeBplusBadge: string;
  gradeBBadge: string;
  viewGradingSlide: string;
  performanceStats: string;
  clientReviewsCount: string;
  badgesTitle: string;
  allGrades: string;
  sortByGrade: string;
  sortByWinRate: string;
  sortByCompromised: string;
  terms: string;
  privacy: string;
  refunds: string;
  grievanceContact: string;
  copyright: string;
  platformServices: string;
  legalCompliance: string;
  merchantSupport: string;
  verifiedAdvocatesDir: string;
  nationalCaseRegistry: string;
  multiTenantVault: string;
  automatedNoticeGen: string;
  aiStatutoryCounsel: string;
  dpdpActPrivacy: string;
  refundCancelPolicy: string;
  grievanceOfficer: string;
  operationalHours: string;
}
